name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Main_build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
    name: Build and run C/C++ ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    # - name: configure
    #   run: ./configure
    # - name: make
    #   run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck

    - name: Build sample
      run: gcc main.c helpers.c -o main -v

    - name: Run sample
      run: ./main