name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Main_build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
    name: Build and run C/C++ ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build sample
      run: |
        mkdir ./bin
        make

    - name: Run sample
      run: make run
